"""
b1 = Book(title="Feed", author="Mira Grant", description="The year was 2014. We had cured cancer. We had beaten the common cold. But in doing so we created something new, something terrible that no one could stop.The infection spread, virus blocks taking over bodies and minds with one, unstoppable command: FEED. Now, twenty years after the Rising, bloggers Georgia and Shaun Mason are on the trail of the biggest story of their lives—the dark conspiracy behind the infected.The truth will get out, even if it kills them.", release=2010)
b2 = Book(title="Zone One", author="Colson Whitehead", description="Written by Colson Whitehead. A virus has laid waste to civilization, turning the infected into flesh-eating and mortally contagious zombies. But events have stabilized, and the rebuilding process has begun. Over a three-day span, 'Mark Spitz' and his fellow 'sweepers'—other survivors of the apocalypse—patrol portions of New York City, eliminating zombies as part of a mission to make the city habitable once again. Flashbacks pepper the narrative, explaining how Mark Spitz survived the apocalypse to date and got his nickname along the way.", release=2011)
b3 = Book(title="Undead Girl Gang", author="Lily Anderson", description="Mila Flores and her best friend Riley have always been inseparable. There's not much excitement in their small town of Cross Creek, so Mila and Riley make their own fun, devoting most of their time to Riley's favorite activity: amateur witchcraft. So when Riley and two Fairmont Academy mean girls die under suspicious circumstances, Mila refuses to believe everyone's explanation that her BFF was involved in a suicide pact. Instead, armed with a tube of lip gloss and an ancient grimoire, Mila does the unthinkable to uncover the truth: she brings the girls back to life.Unfortunately, Riley, June, and Dayton have no recollection of their murders, but they do have unfinished business to attend to. Now, with only seven days until the spell wears off and the girls return to their graves, Mila must wrangle the distracted group of undead teens and work fast to discover their murderer...before the killer strikes again.", release=2018)
l1 = List(title="March 2022", reviewer_id=1)
l2 = List(title="My Favorite Games", reviewer_id=1)
l3 = List(title="Watch With George", reviewer_id=1)

m1 = Movie(title="3 Hours Till Dead", description="An AWOL soldier with PTSD goes into hiding along with his brother and a few friends. They retreat into a rural farm area unaware that the outside world has ceased to function.  On their way back to civilization, his brother is attacked by an infected farmer. He quickly morphs into a rabid animal and lives for exactly three hours. Realizing they are in grave danger, they head back to the forest trying to outlive the legions of the infected.", release=2016)
m2 = Movie(title="8th Plague", description="When Launa’s sister doesn’t return from a camping trip in time for the sisters’ visit to their parent’s grave on the anniversary of their deaths she becomes obsessed with finding out why. Launa recruits a couple of friends to assist in the search, and the small group (along with an unwilling police officer and an even less willing ex-prison guard) soon finds themselves in an abandoned prison, surrounded by an ancient evil. A demonic curse has been unleashed and it seems there is no chance for escape.", release=2006)
m3 = Movie(title="13 Eerie", description="Six forensics undergraduates stay on a remote island to win an esteemed trainee position with the FBI, but no one knows that the site was used as an illegal biological testing ground and, now, horrifying creatures lurk in the shadows.", release=2013)

r1 = Reviewer(username="alixp")

db.session.add(b1)
db.session.add(b2)
db.session.add(b3)
db.session.add(r1)
db.session.add(l1)
db.session.add(l2)
db.session.add(l3)
db.session.add(m1)
db.session.add(m2)
db.session.add(m3)
db.session.commit()
"""




"""
All TV SHOWS - per https://en.wikipedia.org/wiki/Category:Zombies_in_television
t1 = Show(title="Acting Dead", description="Acting Dead is an American satirical dark comedy about the world of Hollywood zombies. The series focuses on Tate Blodgett, a zombie, and Alex Carbonneux, a ghost, as they both struggle with their new afterlife.", seasons=1, release=2014)
t2 = Show(title="All of Us Are Dead", description="After a failed science experiment, a local high school is overrun with zombies, and the trapped students struggle to survive. With no food or water, and communication cut-off by the government, they must use equipment around the school to protect themselves in the midst of a battleground or they will become part of the infected.", seasons=1, release=2022)
t3 = Show(title="American Gods", description="Only days before his scheduled release from prison, Shadow Moon is told his wife has been killed in a car accident, and he is released early to attend the funeral. A series of events delay his trip home, during which time he meets the mysterious Mr. Wednesday. Wednesday repeatedly offers Shadow a job, which he refuses until Wednesday reveals that the job waiting for him at home no longer exists. Shadow accepts the offer to become Wednesday's minder (driver/assistant/bodyguard). Shadow finds himself in a hidden world where magic is real and a collection of 'Old Gods' fear irrelevance in the face of the growing power of a collection of 'New Gods', which include Technology and Media. In a grand plan to combat this deadly threat, Mr. Wednesday attempts to unite the Old Gods to defend their existence and rebuild the influence they have lost, leaving Shadow struggling to accept this new world and his place in it.", release=2017, seasons=3)
t4 = Show(title="American Horror Story: Coven", description="American Horror Story: Coven is the third season of the FX horror anthology television series American Horror Story, created by Ryan Murphy and Brad Falchuk. It premiered on October 9, 2013, and concluded on January 29, 2014. The season takes place in 2013 in New Orleans and follows a coven of witches descended from Salem as they fight for survival. It also features flashbacks to 1692 during the infamous Salem Witch Trials, the 1830s, 1910s, 1960s, 1970s, and 1990s.", release=2013, seasons=1)
t5 = Show(title="Ash vs Evil Dead", description="The series is set approximately 30 years after the first three Evil Dead films, and serves as a sequel to that trilogy. Ash Williams works at the 'Value Stop' as a simple stock boy. Also working at the store is his friend Pablo and the object of Pablo's affections, Kelly. Ash has seemingly done very little with his life since returning from 1300 AD at the end of Army of Darkness, and the beginning of the series sees him living in a trailer and drinking alone in bars. However, Ash must soon renounce his routine existence and become a hero once more by taking up arms and facing the titular Evil Dead. Pablo and Kelly decide to join him on his quest to save humanity.", release=2015, seasons=3)
t6 = Show(title="Betaal", description="Betaal is an Indian zombie horror streaming television series based in a remote village that serves as the battleground between East India Company Army officer Lt. Col John Lynedoch, his battalion of zombie redcoats from the Indian Rebellion of 1857, and the fictional CIPD force.", release=2020, seasons=1)
t7 = Show(title="Black Summer", description="Six weeks after the start of the zombie apocalypse, Rose is separated from her daughter, Anna, and she embarks on a harrowing journey to find her. Thrust alongside a small group of refugees in North America, she must brave a hostile new world and make brutal decisions during the most deadly summer of the apocalypse.", release=2019, seasons=2 )
t8 = Show(title="Chilling Adventures of Sabrina", description="Chilling Adventures of Sabrina is set in the fictional town of Greendale. It is a dark coming-of-age story that includes horror, fear and witchcraft. Sabrina Spellman must reconcile her dual nature as a half-witch, half-mortal while fighting the evil forces that threaten her, her family, and the daylight world humans inhabit.", release=2018, seasons=4)
t9 = Show(title="The Cure", description="The life of Greg, Charity and Hope take a turn when Greg's mother is diagnosed with late-stage cancer. Desperate to find a treatment, Greg gets his hands on an experimental drug made by Evangeline Lazaro and gives it to his mother. The drug becomes the root of an infection that threatens to spread all over the city. Greg, Charity, Evangeline and her son, Joshua will start to find a cure.", release=2018, seasons=1 )
t10 = Show(title="Dark Shadows", description="Dark Shadows is an American gothic soap opera that aired weekdays on the ABC television network, from June 27, 1966, to April 2, 1971. The show depicted the lives, loves, trials, and tribulations of the wealthy Collins family of Collinsport, Maine, where a number of supernatural occurrences take place.", release=1966, seasons=6)
t11 = Show(title="Dead Set", description="Dead Set is a British horror comedy-drama miniseries written and created by Charlie Brooker and directed by Yann Demange. The show takes place primarily on the set of a fictional series of the real television show Big Brother. The five episodes, aired over five consecutive nights, chronicle a zombie outbreak that strands the housemates and production staff inside the Big Brother House, which quickly becomes a shelter from the undead.", release=2008, seasons=1)
t12 = Show(title="Death Valley", description="A year prior to the opening of the series, vampires, werewolves and zombies mysteriously descended upon the streets of California's San Fernando Valley. The newly formed Undead Task Force (UTF), a division of the Los Angeles Police Department, is created to combat the emergence of monsters in the San Fernando Valley. A camera crew is embedded within the task force to document the zombie, vampire and werewolf encounters.", release=2011, seasons=1)
t13 = Show(title="Drop Dead Weird", description="The Champs are an Australian family who move to Tubbershandy, an isolated seaside village in western Ireland to save the Bed & Breakfast run by their Irish grandfather. The three Aussie children Lulu, Bruce and Frankie are finding it hard to fit into a new hometown but also hide the secret that their parents recently became zombies. The kids must keep the truth under wraps from the community and in particular, local identity Bernadette (Bunni) Shanahan.", release=2017, seasons=2)
t14 = Show(title="Fear the Walking Dead", description="Set in Los Angeles, California and later in Mexico, the first three seasons of Fear the Walking Dead follow a dysfunctional, blended family composed of high school counselor Madison Clark, her English teacher fiancé Travis Manawa, her daughter Alicia, her drug addict son Nick, Travis' son from a previous marriage, Chris, Chris' mother Liza Ortiz, and others who join their group at the onset of the zombie apocalypse. They must reinvent themselves, learning new skills and adopting new attitudes in order to survive as civilization collapses around them. Beginning in the fourth season, the series shifts focus toward Morgan Jones, a character from the original series, who encounters the group's surviving members and new survivors in Texas.", release=2015, seasons=7)
t15 = Show(title="Freakish", description="The series follows a group of students who gather for school detention on a Saturday at Kent High. Other students are on campus as well, but involved in various activities (basketball, debate prep, music, etc.). When a nearby chemical plant explodes, they must work together to find a way to survive with only limited resources and protect themselves from those who have turned into freakish zombie-like creatures as a result of the fallout.", release=2016, seasons=2)
t16 = Show(title="Galavant", description="A musical comedy adventure featuring a knight on a quest for love who helps a childish king to see the error of his ways.", release=2015, seasons=2)
t17 = Show(title="Game of Thrones", description="Game of Thrones is roughly based on the storylines of the A Song of Ice and Fire book series by George R. R. Martin, set in the fictional Seven Kingdoms of Westeros and the continent of Essos. The series follows several simultaneous plot lines. The first story arc follows a war of succession among competing claimants for control of the Iron Throne of the Seven Kingdoms, with other noble families fighting for independence from the throne. The second concerns the exiled scion's actions to reclaim the throne; the third chronicles the threat of the impending winter, as well as the legendary creatures and fierce peoples of the North.",release=2011, seasons=8)
t18 = Show(title="The Haunting Hour: The Series", description="R. L. Stine's The Haunting Hour: The Series is an original anthology horror-fantasy television series which is based on the 2007 movie R.L Stine's The Haunting Hour: Don't Think About It and the anthologies The Haunting Hour and Nightmare Hour by R.L. Stine. Like Goosebumps, every episode features a different cast in a scary situation that would involve ghosts, aliens, witches, zombies, and monsters. However, the storylines are much darker than its aforementioned predecessor and some episodes serve as very dark morality tales. Unlike the Goosebumps series, the threat of death is not implied, being both clear and permanent. In addition, death in the show is not limited to antagonists and minor characters with some stories even ending with the main protagonist(s) being killed. However, there are some episodes that have happy endings similar to most of the episodes of Are You Afraid of the Dark? which had this formula.", release=2010, seasons=4)
t19 = Show(title="Helix", description="The series followed a team of scientists from the Centers for Disease Control and Prevention (CDC) who traveled to a research facility in the Arctic to investigate a potential outbreak of disease. While there, they find themselves stuck in a life-or-death situation that could decide the future of mankind.", release=2014, seasons=2)
t20 = Show(title="Highschool of the Dead", description="Highschool of the Dead is set in present-day Japan, beginning as the world is struck by a deadly pandemic that turns humans into zombies, euphemistically referred to by the main characters as 'Them' (奴ら, Yatsu-ra). The story follows a group of high school students and the school's nurse as they deal with the worldwide catastrophic event known as the 'Outbreak'. As the cast tries to survive the zombie apocalypse, they must also face the additional threats of societal collapse, in the form of dangerous fellow survivors, and the possible decay of their own moral codes. Starting from the high school, the students escape into town where they must deal with a corrupt teacher and his students. They check their homes for survivors, and pick up a little girl and a dog. Later, they hole up at a mall, travel through a police station, and eventually make their way to an elementary school that is supposedly a safe zone.", release=2010, seasons=1)
t21 = Show(title="I Survived a Zombie Apocalypse", description="The show is centered on a group of contestants who must survive for seven days in an abandoned shopping centre overrun by zombies set six months after exposure to '5G Wifi'. They have to make base, secure food, shelter and safety, and complete tasks set by the army. After seven days the army will evacuate any survivors out of the area to a 'global tropical quarantine area'.", release=2015, seasons=1)
t22 = Show(title="In the Flesh", description="The show, set in the fictional village of Roarton, Lancashire, though filmed in Marsden, West Yorkshire, depicts life several years after 'The Rising'. This period, in (fictional) 2010, was a time when thousands of people who had died in 2009 suddenly re-animated as mindless, homicidal, brain-eating zombies world-wide. However, by the time of the series, normality has begun to return. A full-fledged zombie apocalypse has long since been prevented by armed resistance from the living, especially from armed local militias who patrolled their communities and actively hunted the re-animated. Meanwhile, a scientific solution for the zombie phenomenon has been found, with the development of a medication to restore consciousness to the undead, allowing them to remember their time alive and who they once were. The surviving undead, not killed by the militias, have been rounded up, forcibly medicated, and entered in a government rehabilitation programme in a plan to reintroduce them to society. They are provided with contact lenses and cosmetics, to help them conceal their deceased status, and maintenance injections of medication to keep them from relapsing into a dangerous or 'rabid' state. They are officially referred to as sufferers of Partially Deceased Syndrome (PDS), though anti-zombie hardliners prefer the pejorative term 'rotters'. Many of the risen are haunted by memories of the atrocities they committed while rabid. In the village of Roarton, PDS sufferers face prejudice from the villagers upon their return.", release=2013, seasons=2)
t23 = Show(title="Is This a Zombie?", description="Ayumu Aikawa is a zombie who was once an ordinary high schooler resurrected by a necromancer named Eucliwood Hellscythe after being murdered by a serial killer. As he tries to make the best of his undead life, he encounters a Masō-Shōjo (魔装少女, lit. Magical Garment Girl, a pun on 'mahō shōjo,' meaning magical girl) named Haruna and inadvertently takes her magic powers, being forced to become a Masō-Shōjo in the process. With Eucliwood, Haruna, and a vampire ninja named Seraphim living with him, Ayumu helps battle demons known as Megalos while trying to figure out the mystery behind his own death.", release=2011, seasons=2)
t24 = Show(title="iZombie", description="Seattle medical resident Olivia 'Liv' Moore is turned into a zombie while attending a boat party. She abandons her career and breaks up with her fiancé, much to the disappointment and puzzlement of her family. She discovers that if she does not periodically satisfy her new appetite for brains, she will turn into a stereotypically primitive and homicidal zombie. Instead of feeding by killing innocent people, Liv decides to take a job at the King County morgue and eat the brains of the corpses she autopsies.", release=2015, seasons=5)
t25 = Show(title="Kamen Rider 555", description="The Smart Brain corporation, the world's most powerful corporation, is trying to take over the world using Orphnoch, the 'next stage in humanity's evolution', to covertly kill off the human population. In pursuit of this, they develop three suits of power armor, called Rider Gears (each for Delta, Faiz, and Kaixa), to find and protect the Orphnoch King, who can fix a defect within Orphnoch DNA which causes their genetic structure to break down, leading to death.", release=2003, seasons=1)
t26 = Show(title="Kingdom", description="Set during Korea's Joseon Dynasty, three years after the Imjin War, the first season of Kingdom follows the story of Crown Prince Lee Chang and his subordinates, who stumble across an unnatural plague that resurrects the dead amidst their investigation of a brewing political conspiracy and rumors of the King of Joseon's death. Amidst the chaos and death that ensues, Chang meets allies who try to make a stand in the city-state of Sangju before it spreads further into the province, only to discover that the plague has already adapted. The second season picks up during Lee Chang's struggle to save his people from the spread of the plague and his dynasty from the machinations of the powerful Haewon Cho clan who hides a sinister secret.", release=2019, seasons=2)
t27 = Show(title="The Last Reality Show", description="The show portrays a zombie apocalypse as seen through the eyes of the cast and crew of a reality show. The title of the series refers to the name of said reality show being produced which is to bring forth the ultimate Swedish reality star (reality show stars of Swedish reality shows play themselves) as well that the fact that almost every episode features the death of one of the reality stars.", release=2012, seasons=1)
t28 = Show(title="My Dead Ex", description="Charley is a normal high school girl with a crush on a cute boy. As she tries to score a date with the cute boy named Luke, her annoying ex, Ben Bloom, will do anything to get her to go on a date with him. Ever since she dumped him, she wanted nothing to do with him, but when he dies, things start to change.", release=2018, seasons=1)
t29 = Show(title="Parasite Island", description="In a remote island village off the coast of mainland Luzon, a legend about mysterious, invasive and parasitic leeches that turn people into zombie-like state intertwines the stories of its past victim, the village man, and the current one, the family of a young father on the edge of falling apart due to a festering infighting.", release=2013, seasons=1)
t30 = Show(title="Pushing Daisies", description="Pushing Daisies centers on the life of Ned, a pie-maker gifted with the ability to reanimate the dead by touching them. If something is revived for more than one minute, a similar 'life value' in the vicinity drops dead as a form of balance. If he touches the revived person or thing a second time, they die permanently.", release=2007, seasons=2)
t31 = Show(title="Reality Z", description="The successful reality show Olympus, where TK, Jessica, Augusto, Marcos, Veronica, Madonna and Cleide were confined, is interrupted when a zombie apocalypse takes over Rio de Janeiro, forcing the production and the cast to remain locked up in the studios. A production runner, Nina, leads the fight against monsters.", release=2020, seasons=1)
t32 = Show(title="The Returned", description="In a small French mountain town many dead people reappear apparently alive and normal, including teenage school bus crash victim Camille, suicidal bridegroom Simon, a small boy called 'Victor' who was murdered by burglars, and serial killer Serge. While they try to resume their lives, strange phenomena take place: recurring power outages; a mysterious lowering of the local reservoir's water level, revealing the presence of dead animals and a church steeple; and the appearance of strange marks on the bodies of the living and the dead.", release=2012, seasons=2)
t33 = Show(title="Santa Clarita Diet", description="Joel and Sheila Hammond are everyday suburban real estate agents in Santa Clarita, California. The couple face a series of obstacles when Sheila undergoes a metamorphosis, becomes undead and starts craving human flesh. As Joel and the family try to help Sheila through this, they have to deal with neighbors and cultural norms, and get to the bottom of a potentially mythological mystery.", release=2017, seasons=3)
t34 = Show(title="Teenage Euthanasia", description="In the mildly apocalyptic near future, Trophy Fantasy is a teenage mother who left her baby daughter Euthanasia 'Annie' Fantasy in the custody of her undertaker mother Baba and her half-brother Pete at their funeral home Tender Endings in the fictional town of Fort Gator, Florida. After getting a devastating divorce from her current husband and dying from an overdose 15 years later, Trophy's corpse is delivered to Baba at Tender Endings as her written demand to those who found her dead. An unexpected combination of Baba's embalming fluid, Annie's tears, and a lightning bolt from a thunderstorm revives Trophy as a sentient zombie with supernatural abilities that involves housing a swarm of sentient beetles in her crotch.", release=2021, seasons=1)
t35 = Show(title="Ugly Americans", description="An upbeat, mild-mannered man named Mark Lilly moves to Manhattan, which is inhabited by humans and a wide variety of non-human and demonic species. He becomes a social worker with the Social Services Division of the Department of Integration, a sub-set of the U.S. Department of Homeland Security, which specializes in facilitating the integration of the non-humans into the city. Mark lives with a lazy, over-sexed zombie roommate and has a wizard co-worker and a demon boss. His succubus girlfriend, who also works at the Department of Integration, is the daughter of Satan (who is trying to bring about the end of days) and a human who 'looks like Mia Farrow in Rosemary's Baby'. Mark struggles to stay cheerful and politically correct while working with his bizarre and frequently dangerous companions.", release=2010, seasons=2)
t36 = Show(title="The Walking Dead", description="The Walking Dead takes place after the onset of a worldwide zombie apocalypse. The zombies, referred to as 'walkers', shamble towards living humans and other creatures to eat them; they are attracted to noise, such as gunshots, and to different scents, e.g. humans. Although it initially seems that only humans that are bitten or scratched by walkers can turn into other walkers, it is revealed early in the series that all living humans carry the pathogen responsible for the mutation. The mutation is activated after the death of the pathogen's host, and the only way to permanently kill a walker is to damage its brain or destroy the body entirely, such as by cremating it. The series centers on sheriff's deputy Rick Grimes, who wakes up from a coma. While in a coma, the world has been taken over by walkers. He becomes the leader of a group of survivors from the Atlanta, Georgia, region as they attempt to sustain and protect themselves not only against attacks by walkers but by other groups of survivors willing to use any means necessary to stay alive.", release=11, seasons=2010)
t37 = Show(title="The Walking Dead: World Beyond", description="The series, set in Nebraska ten years after the zombie apocalypse, features four teenage protagonists and focuses on 'the first generation to come-of-age in the apocalypse as we know it. Some will become heroes. Some will become villains. In the end, all of them will be changed forever. Grown-up and cemented in their identities, both good and bad.'", release=2020, seasons=2)
t38 = Show(title="Z Nation", description="Z Nation begins three years into a zombie apocalypse caused by a virus that has already killed most humans. In the days just before society fell apart, Murphy was one of three inmates at Portsmouth Naval Prison in Kittery, Maine, who were unwilling participants in a government-approved experiment. Each inmate was given a different test vaccine. Murphy was the only one to survive the vaccine injection. He is the only known survivor of a zombie bite who did not turn into a zombie, and his blood contains antibodies that are humankind's last and best hope for a vaccine. However, he seems to be mutating into some form of hybrid between zombie and human—his skin is shedding and his body turning blue, and he seems to be able to control and even mesmerize certain types of zombies that he encounters; yet he has not turned into a full zombie and still maintains control of himself. The series revolves around his travels with a small group of survivors being led through the apocalypse by Simon 'Citizen Z' Cruller, who watches the world from his multiple computers. The group is looking to use him to solve the zombie pandemic.", release=2014, seasons=5)
t39 = Show(title="Zombie Hunters: City of the Dead", description="Zombie Hunters: City of the Dead is an independent television series produced in New York City, notable as being the first broadcast zombie-based television series. It details the lives of a group of friends banding together to survive the epidemic resurrection of dead humans. These re-animated corpses are driven by a need to feed, and only attack living humans. The main character of Billy Cassidy is an Irish Catholic whose violent actions are in direct conflict with his faith, often resulting in an inner conflict that quickly manifests itself in external ways. Paul Michael Bates and John Salazar are Cassidy's main partners, and they are later joined by Dr Rebecca Kaufman and Carrie Walker, RN. This constitutes the first main group of 'hunters' in the first season.", release=2007, seasons=2)
t40 = Show(title="Zombie Land Saga", description="In the year 2008, high school student Sakura Minamoto is abruptly killed by a truck on the morning she plans to submit an idol application. Ten years later, Sakura, along with six 'legendary' girls from various eras of Japan's history, are brought back as zombies by a man named Kotaro Tatsumi, who seeks to revitalize Saga Prefecture by putting together an all-zombie idol group that would become known as Franchouchou.", release=2018, seasons=1)

db.session.add(t1)
db.session.add(t2)
db.session.add(t3)
db.session.add(t4)
db.session.add(t5)
db.session.add(t6)
db.session.add(t7)
db.session.add(t8)
db.session.add(t9)
db.session.add(t10)
db.session.add(t11)
db.session.add(t12)
db.session.add(t13)
db.session.add(t14)
db.session.add(t15)
db.session.add(t16)
db.session.add(t17)
db.session.add(t18)
db.session.add(t19)
db.session.add(t20)
db.session.add(t21)
db.session.add(t22)
db.session.add(t23)
db.session.add(t24)
db.session.add(t25)
db.session.add(t26)
db.session.add(t27)
db.session.add(t28)
db.session.add(t29)
db.session.add(t31)
db.session.add(t32)
db.session.add(t33)
db.session.add(t34)
db.session.add(t35)
db.session.add(t36)
db.session.add(t37)
db.session.add(t38)
db.session.add(t39)
db.session.add(t40)



ADD ALL GAMES!
g1= Game(title=7 Days to Die, release=2013, platforms=Linux  macOS  Windows  PlayStation 4, description=An open-world  voxel-based  role-playing survival RPG set in the aftermath of a third world war. The player controls a survivor trapped in Arizona in the year 2034  where zombies run rampant after an unknown virus infects the remaining surviving population. The player must find food  water  weapons  and other supplies  as well as craft and build up defenses to survive against the relentless horde of the undead.)																							
db.session.add(g1)																							
g2= Game(title=Alive 4-Ever, release=2009, platforms=iOS, description=Overhead shooter game where the player picks one of four characters and attempts to stave off a zombie horde whilst completing objectives.)																							
db.session.add(g2)																							
g3= Game(title=All Zombies Must Die!, release=2011, platforms=PlayStation 3  Windows  Xbox 360, description=A downloadable top-down view shooter game with role-playing game elements. Up to four players must survive a zombie apocalypse. The sequel to Burn Zombie Burn!)																							
db.session.add(g3)																							
g4= Game(title=Alone in the Dark 3, release=1994, platforms=DOS  Mac OS  Windows, description=Survival horror game set in an Old West ghost town. Paranormal investigator Edward Carnby must rescue Emily Hartwood  the other playable character from Alone in the Dark from a band of zombie outlaws.)																							
db.session.add(g4)																							
g5= Game(title=Amy, release=2012, platforms=PlayStation 3  Xbox 360, description=Downloadable survival horror game. A scientist must escort an eight-year-old girl through a city devastated by an airborne virus that turns those infected into zombies. The scientist is infected and must manage her condition.)																							
db.session.add(g5)																							
g6= Game(title=Area 51, release=1995, platforms=Arcade  PlayStation  Sega Saturn  Windows, description=Light gun game where players fight off an alien infestation inside Area 51 while fighting the personnel  who have been turned into zombies.)																							
db.session.add(g6)																							
g7= Game(title=Atom Zombie Smasher, release=2011, platforms=Linux  macOS  Windows, description=Real time strategy game viewed from a top-down perspective where players must coordinate military units in order to rescue civilians from a zombie horde.)																							
db.session.add(g7)																							
g8= Game(title=Back 4 Blood, release=2021, platforms=Microsoft Windows  Playstation  Xbox, description=First person shooter  survival horror game which is a spiritual successor to Left 4 Dead.)																							
db.session.add(g8)																							
g9= Game(title=Beast Busters, release=1989, platforms=Amiga  Arcade  Atari ST, description=Light gun game for up to three players  who must shoot their way out of a zombie-infested city with submachine guns.)																							
db.session.add(g9)																							
g10= Game(title=Blood, release=1997, platforms=DOS, description=First-person shooter game set in the 1920s. The player plays as an undead henchman on a quest for revenge. Zombies are common enemies the player will face in almost every level.)																							
db.session.add(g10)																							
g11= Game(title=Blood Drive, release=2010, platforms=PlayStation 3  Xbox 360, description=Vehicular combat game featuring six arenas filled with zombies  players control drivers who must either defeat zombies or other drivers  dependent on which level is being played.)																							
db.session.add(g11)																							
g12= Game(title=Burn  Zombie Burn!, release=2009, platforms=PlayStation 3  Windows  macOS , description=Zombies appear in waves and must be destroyed by being set alight.)																							
db.session.add(g12)																							
g13= Game(title=Call of Duty: Black Ops (zombie mode), release=2010, platforms=PlayStation 3  Xbox 360  Windows, description=First-person shooter survival mode of Call of Duty: Black Ops. A zombie cooperation mode  titled 'Zombies'  is included in the game. Originally featured in World at War  it was revamped to be included in Black Ops. It is a four-player online and two-player split screen co-op mode (which can also be unlocked online). Based on the original game  in the map 'Five'  players take the roles of John F. Kennedy  Richard Nixon  Robert McNamara  and Fidel Castro as they fight zombies at the Pentagon. Another map  called Kino der Toten ('Theater/Cinema of the Dead' in German)  features the characters from World at War – Edward Richtofen the German  Tank Dempsey the American  Takeo Masaki the Japanese  and Nikolai Belinski the Russian. Limited editions of the game offer graphically-enhanced versions of the four zombie maps from World at War  featuring the newer weapons from the rest of the game. There is an unlockable top-down  two-stick arcade-shooter version of Zombies known as Dead Ops Arcade.)																							
db.session.add(g13)																							
g14= Game(title=Call of Duty: Black Ops – Zombies, release=2011, platforms=iOS  Android, description=First-person shooter spin off from the Zombies minigame in Call of Duty: Black Ops  up to four players can co-operate using voice chat to survive the zombie onslaught.)																							
db.session.add(g14)																							
g15= Game(title=Call of Duty: Black Ops II (zombie mode), release=2012, platforms=PlayStation 3  Xbox 360  Windows, description=First-person shooter survival game  part of the Call of Duty: Black Ops II. Treyarch has confirmed that the Zombies mode will return for Black Ops II with new game modes. Its predecessors were Call of Duty: World at War and Call of Duty: Black Ops. This is the third time for the Zombies mode to appear in a Call of Duty game  and the first time to have game modes other than the traditional Survival mode. Treyarch has also confirmed that Zombies will run on the game's multiplayer engine  allowing for a deeper community experience  along with new features. A new 8 player co-op game called Grief is also supported  featuring 2 teams of 4 players competing to survive  unlike Call of Duty: World at War and Call of Duty: Black Ops  which only supported 4 player online co-op. As with the previous game  each map contains 'Easter eggs' side quests  which is used to progress the story.)																							
db.session.add(g15)																							
g16= Game(title=Call of Duty: Black Ops III (zombie mode), release=2015, platforms=Microsoft Windows  PlayStation 4  Xbox One, description=First-person shooter survival horror video game  part of Call of Duty: Black Ops III. Treyarch confirmed  zombies will return in Call of Duty: Black Ops III  with an alternative expanded campaign. The classic survival horde mode from previous titles returns. The storyline from the previous games is also continued as the four characters; Tank Dempsey  Takeo Masaki  Nikolai Belinski and Doctor Edward Richtofen attempt to save the universe.)																							
db.session.add(g16)																							
g17= Game(title=Call of Duty: Black Ops 4 (zombie mode), release=2018, platforms=Microsoft Windows  PlayStation 4  Xbox One, description=First-person shooter horror-themed video game mode  part of Call of Duty: Black Ops 4.)																							
db.session.add(g17)																							
g18= Game(title=Call of Duty: Black Ops Cold War (zombie mode), release=2020, platforms=PlayStation 4  PlayStation 5  Xbox One  Xbox Series X  Microsoft Windows, description=First-person shooter survival horror video game  part of Call of Duty: Black Ops Cold War. Unlike previous titles  Call of Duty: Black Ops Cold War's zombie mode does not have 4 main protagonists  instead playing as operators from the Multiplayer mode.)																							
db.session.add(g18)																							
g19= Game(title=Call of Duty: Infinite Warfare (zombie mode), release=2016, platforms=PlayStation 4  Xbox One  Windows, description=Zombies is a game mode that is featured in Call of Duty: Infinite Warfare. The first map is called Zombies in Spaceland.)																							
db.session.add(g19)																							
g20= Game(title=Call of Duty: World at War (zombie mode), release=2008, platforms=PlayStation 3  Xbox 360  Windows, description=First-person shooter survival mode of Call of Duty: World at War. All versions but the Wii feature the minigame Nazi Zombies  which consists of 1-4 players fighting an unlimited number of waves of Nazi zombies. Players can work together with other people to assassinate the zombies in a 'co-op' (cooperative) mode either offline with two players or online with 2-4 players. The players gain points by injuring or killing the zombies or repairing boarded-up windows  which are used to remove blockages inside the bunker and to gain access to more useful weapons than the starting M1911 pistol and unlock more rooms. Zombies continually break the windows to gain entrance and to find and beat the players; when all players are damaged enough to fall  the game is over. Three extra maps for the Nazi Zombies game mode were added with the World at War map packs. These maps  Shi No Numa  Verruckt and Der Riese added on to the Nacht Der Untoten map which came with the game.)																							
db.session.add(g20)																							
g21= Game(title=Call of Duty: World at War – Zombies, release=2009, platforms=iOS, description=First-person shooter set during World War II where a military bunker must be defended from attacking Nazi zombie soldiers. Based on the zombie mode of Call of Duty: World at War.)																							
db.session.add(g21)																							
g22= Game(title=CarnEvil, release=1998, platforms=Arcade, description=Light gun game set in an undead-infested amusement park.)																							
db.session.add(g22)																							
g23= Game(title=Carrier, release=2000, platforms=Dreamcast, description=Survival horror  an explosion aboard a large ship has released a virus which transforms the infected into mutants similar to the Resident Evil zombies.)																							
db.session.add(g23)																							
g24= Game(title=Cataclysm: Dark Days Ahead, release=2013, platforms=PC  Mobile, description=Hardcore rogue-like adventure game set in a post apocolyptic world  featuring a wide variety of zombies as well as Triffids  Fungal Monsters  and otherworldy creatures such as Flaming Eyes. The game features robust systems for character traits  stats  skills  and a very wide variety of items  vehicles  buildings  and map features randomly generated when each word is created. This game is still in development with an open source code.)																							
db.session.add(g24)																							
g25= Game(title=Contagion, release=2014, platforms=Windows, description=Contagion is a zombie survival horror title by Monochrome Games and is the spiritual successor to the Half-Life 2 mod Zombie Panic: Source.)																							
db.session.add(g25)																							
g26= Game(title=Corpse Craft: Incident at Weardd Academy, release=2008, platforms=Browser  Flash  iOS, description=A simplified real-time strategy game in which schoolchildren battle each other with zombies they reanimate.)																							
db.session.add(g26)																							
g27= Game(title=Corpse Killer, release=1994, platforms=3DO  Sega CD  32X  Sega Saturn  Windows, description=A live-action light gun game featuring a soldier who must fight through an island full of zombies to reach 'necrobiologist' Dr. Hellman.)																							
db.session.add(g27)																							
g28= Game(title=D2, release=2000, platforms=Dreamcast, description=Survival horror  the survivor of a plane crash in the wilds of Canada discovers that other passengers on the plane are being transformed into zombie-plant hybrids.)																							
db.session.add(g28)																							
g29= Game(title=Darkwatch, release=2005, platforms=PlayStation 2  Xbox, description=First-person shooter in a Wild West setting. A train robber turned vampire must defeat enemies such as zombies and skeletons while trying to reclaim his humanity.)																							
db.session.add(g29)																							
g30= Game(title=Days Gone, release=2019, platforms=PlayStation 4  Windows, description=An open-world action-adventure game where you play as Deacon St. John  a Drifter and bounty hunter who would rather risk the dangers of the broken road than live in one of the 'safe' wilderness encampments. The game takes place two years after a global pandemic has killed almost everyone  but transformed millions of others into what survivors call Freakers.)																							
db.session.add(g30)																							
g31= Game(title=DayZ, release=2012, platforms=Windows, description=An ARMA 2 mod which features survival horror and shooter gameplay in an open world. The game is online multiplayer. Players must feed their character as well as deal with other players and the living dead. The mod now also has a stand-alone version for PC owners.)																							
db.session.add(g31)																							
g32= Game(title=Dead Block, release=2011, platforms=PlayStation 3  Windows  Xbox 360, description=Players must barricade themselves within a building while exploring to find items in order to complete each level.)																							
db.session.add(g32)																							
g33= Game(title=Dead Effect series, release=2013, platforms=iOS  Android  Microsoft Windows  macOS  PlayStation 4  Xbox One, description=The Dead Effect series is a horror  first-person shooter  RPG  zombie game developed and published by BadFly Interactive a.s. The second release features a co-operative Multiplayer and PvP Multi-player. the player has to battle with zombies  soldiers  bosses and cyberdogs to gain points and cash for buying and upgrading weapons  amour  etc. The game contains a story mode and other missions like generic  survival  bio-hazard  etc.)																							
db.session.add(g33)																							
g34= Game(title=Dead Frontier, release=2008, platforms=Browser, description=Free browser-based top down massively multiplayer online role-playing game set in an open world. Dead Frontier takes place in a post-apocalypse setting teeming with zombies. Players must scavenge supplies in order to survive.)																							
db.session.add(g34)																							
g35= Game(title=Dead Head Fred, release=2007, platforms=PlayStation Portable, description=Private investigator Fred is murdered  only to find himself reanimated and able to steal enemies' heads to perform different attacks.)																							
db.session.add(g35)																							
g36= Game(title=Dead Island series, release=2011–present, platforms=PlayStation 3  PlayStation 4  Windows  Xbox 360  Xbox One, description=Single-player or multiplayer open world games with role-playing elements and an emphasis on combat. Upcoming releases include a new game in the main series  a stealth-focused spinoff and a MOBA game.)																							
db.session.add(g36)																							
g37= Game(title=Dead Nation, release=2010, platforms=PlayStation 3, description=PlayStation Network twin-stick shooter. The game detects players' geographic locations and groups them accordingly within the game world  displaying players' progress in that region.)																							
db.session.add(g37)																							
g38= Game(title=Dead Rising series, release=2006–present, platforms=iOS  PlayStation 3  Wii  Windows  Xbox 360  Xbox One, description=Third-person action games which allow the player to destroy zombies with various ordinary items and weapons  from benches and lawnmowers to guns and swords.)																							
db.session.add(g38)																							
g39= Game(title=Dead Space series, release=2008–2013, platforms=PlayStation 3  Wii  Windows  Xbox 360, description=Science fiction survival horror games where Necromorphs  generated from corpses infected by an alien pathogen  are the primary enemy. They are most effectively killed by 'strategic dismemberment'  cutting off their limbs.)																							
db.session.add(g39)																							
g40= Game(title=Dead State, release=2014, platforms=Windows, description=Role-playing game with turn-based combat set in the fictional town of Splendid  Texas. Players must defend their shelter while foraging for supplies and recruiting survivors.)																							
db.session.add(g40)																							
g41= Game(title=Deadlight, release=2012, platforms=Windows  Xbox 360, description=Side-scrolling survival-horror game.)																							
db.session.add(g41)																							
g42= Game(title=Die2Nite, release=2008, platforms=Browser, description=The players are randomly divided into groups of 40  and each group is allocated within a small town where they must survive as long as possible. Every night at midnight (23:00 game time) the zombies launch an attack on the town.)																							
db.session.add(g42)																							
g43= Game(title=Doom series, release=1993-presents, platforms=MS-DOS  Windows, description=First-person shooter survival horror game with zombies  demons  monsters and other occultist creatures.)																							
db.session.add(g43)																							
g44= Game(title=Dying Light, release=2015, platforms=PlayStation 4  Windows  Xbox One, description=Open World survival horror game set in the fictional quarantined city of Harran  an expansive urban environment overrun by a vicious outbreak. The player is sent to infiltrate the city and must survive by relying on parkour free-running and traps  while scavenging resources and crafting weapons to defend against the growing infected population.)																							
db.session.add(g44)																							
g45= Game(title=Dying Light 2, release=2022, platforms=PlayStation 5  PlayStation 4  Windows  Xbox One  Xbox Series X/S  Nintendo Switch, description=Open World survival horror game set in the last bastion of humanity  city of Villedor  an expansive environment overrun by a vicious outbreak. The player is gone to the city searching for his sister. He must survive by relying on parkour free-running and traps  paraglider and hooker  while scavenging resources and crafting weapons to defend against the growing infected population.)																							
db.session.add(g45)																							
g46= Game(title=Entombed, release=1982, platforms=Atari 2600, description=From a top-down perspective  the player must make their way through an endless  vertically-scrolling maze filled with zombies.)																							
db.session.add(g46)																							
g47= Game(title=The Evil Dead, release=1984, platforms=Commodore 64  ZX Spectrum, description=Downloadable survival horror game. A scientist must escort an eight-year-old girl through a city devastated by an airborne virus that turns those infected into zombies. The scientist is infected and must manage her condition.)																							
db.session.add(g47)																							
g48= Game(title=Evil Dead series, release=2000–2005, platforms=Dreamcast  PlayStation  PlayStation 2  Windows  Xbox, description=Action game trilogy consisting of Hail to the King  A Fistful of Boomstick and Regeneration. Ash Williams fights against Deadites  'zombified demons')																							
db.session.add(g48)																							
g49= Game(title=The Evil Within series, release=2014–2017, platforms=PlayStation 3  PlayStation 4  Windows  Xbox 360  Xbox One, description=A gory survival horror game played from a third person viewpoint. Contains both stealth and action sequences. Zombies must be dispatched and burned to prevent them returning to life.)																							
db.session.add(g49)																							
g50= Game(title=Five Nights at Freddy's 3, release=2015, platforms=Windows  iOS  Android  PlayStation 4  Xbox One  Nintendo Switch, description=Point-and-click survival horror game. Main antagonist of the game is Springtrap  the reanimated corpse of the series' overarching villain William Afton. Afton was killed by mechanical failures of an animatronic rabbit costume he had used in committing the murders of several children in the '80s. Springtrap/Afton reappears in subsequent games progressively desiccated and damaged as Scraptrap (Freddy Fazbear's Pizzeria Simulator) and Burntrap (Five Nights at Freddy's: Security Breach).)																							
db.session.add(g50)																							
g51= Game(title=Flesh Feast, release=1998, platforms=Windows, description=3D game in which the player must guide either a team of four characters or a single character through 17 stages of play  rescuing survivors and fighting zombies.)																							
db.session.add(g51)																							
g52= Game(title=Fort Zombie, release=2009, platforms=Windows, description=Players must barricade themselves within a building and survive a zombie onslaught.)																							
db.session.add(g52)																							
g53= Game(title=Ghosts and Goblins, release=1985, platforms=Amiga  Arcade  Commodore 64  Commodore 16  NES, description=is a side-scrolling platforming game developed by Capcom for video arcades and has since been released on several other platforms. It is the first game in the Ghosts 'n Goblins franchise.)																							
db.session.add(g53)																							
g54= Game(title=Ghoul Patrol, release=1994, platforms=Super NES, description=Sequel to Zombies Ate My Neighbors. The local library's goblin exhibit has come to life  the ghoul patrol must fight historical figures who have become zombies as well as other monsters.)																							
db.session.add(g54)																							
g55= Game(title=Gloom 3, release=1997, platforms=Amiga, description=First-person shooter  the player dispenses with zombies which explode in a shower of limbs.)																							
db.session.add(g55)																							
g56= Game(title=H1Z1: Just Survive, release=2015, platforms=Windows, description=MMO open world survival game set in a post-apocalyptic rural United States infected by the H1Z1 outbreak; an effective and intense mutation of the H1Z1 virus. The player must survive with emphasis on mainly crafting  cooperation  and scavenging resources against the swarming zombie population  vicious animals such as wolves and bears  and potentially hostile survivors.)																							
db.session.add(g56)																							
g57= Game(title=Half-Life series, release=1998–2020, platforms=Windows  macOS  Several consoles, description=The player confronts several alien lifeforms that invaded Earth due to a teleport accident. The most prominent foes are humans zombified by some aliens called 'headcrabs'.)																							
db.session.add(g57)																							
g58= Game(title=Horror Zombies from the Crypt, release=1990, platforms=Amiga  Atari ST  DOS, description=Platform game where the player enters a mansion full of zombies and other ghastly creatures.)																							
db.session.add(g58)																							
g59= Game(title=How To Survive, release=2013, platforms=PlayStation 3  Windows  Xbox 360  Wii U, description=Twin-stick shooter game where the player must maintain their character's survival needs. A crafting system is included.)																							
db.session.add(g59)																							
g60= Game(title=The House of the Dead series, release=1996–2013, platforms=Arcade  Dreamcast  Sega Saturn  Wii  Windows  Xbox, description=Gory light gun Arcade games on rails which feature numerous zombies. It is credited with introducing fast running zombies.)																							
db.session.add(g60)																							
g61= Game(title=Human Element, release=Pre-release, platforms=PlayStation 4  Wii U  Windows  Xbox One, description=Survival game set 35 years after a zombie apocalypse. Players must try to rebuild civilization.)																							
db.session.add(g61)																							
g62= Game(title=Hunter: The Reckoning series, release=2002–2003, platforms=GameCube  PlayStation 2  Xbox, description=Trilogy of action games based on the role-playing game  one or more players are tasked with defeating the undead evil that manifests in the town of Ashcroft.)																							
db.session.add(g62)																							
g63= Game(title=I Made a Game with Zombies in It!, release=2009, platforms=Xbox 360, description=Released on Microsoft's Xbox Live Indie Games channel  up to four players shoot droves of attacking enemies  including zombies  while collecting power-ups.)																							
db.session.add(g63)																							
g64= Game(title=Infected, release=2005, platforms=PlayStation Portable, description=Fast-paced shooter game set two weeks before Christmas in New York City. Players assume the role of a rookie police officer and must rescue civilians from the marauding undead.)																							
db.session.add(g64)																							
g65= Game(title=Infestation: Survivor Stories, release=2012, platforms=Windows, description=A survival horror game similar to DayZ in which the player must survive for as long as possible. A lot of controversy has surrounded this game due to its close resemblance to DayZ.)																							
db.session.add(g65)																							
g66= Game(title=Isle of the Dead, release=1993, platforms=DOS, description=First-person shooter with adventure game elements  the player is stranded on an island filled with zombies.)																							
db.session.add(g66)																							
g67= Game(title=Judge Dredd: Dredd Vs. Death, release=2003, platforms=GameCube  PlayStation 2  Windows  Xbox, description=First-person shooter  Judge Dredd faces numerous zombies  vampires and mutants whilst attempting to stop Judge Death from destroying the world's population.)																							
db.session.add(g67)																							
g68= Game(title=Killing Floor or Killing Floor 2, release=2005, platforms=Linux  macOS  Windows, description=A multi-player mod of the Unreal Engine later released as a standalone game. Players assume the role of squad members that must stop increasingly powerful waves of zombie-like clone soldiers.)																							
db.session.add(g68)																							
g69= Game(title=Land of the Dead: Road to Fiddler's Green, release=2005, platforms=Windows  Xbox, description=First-person shooter set within the same universe as the George Romero film Land of the Dead. Players control Jack  a farmer who must fight through different environments in order to find safety within the City of the Living.)																							
db.session.add(g69)																							
g70= Game(title=The Last Guy, release=2008, platforms=PlayStation 3, description=An overhead-perspective rescue game in which the player character is a humanity-loving zombie who must guide civilians to escape points in monster-infested cities.)																							
db.session.add(g70)																							
g71= Game(title=The Last of Us, release=2013, platforms=PlayStation 3, description=An action-adventure survival horror video game. Played from a third-person perspective; players use firearms and improvised weapons  and can use stealth to defend against hostile humans and cannibalistic creatures. Considered to be one of the greatest video games of all time  it won year-end accolades  including multiple Game of the Year awards from several gaming publications  critics  and game award shows  making it one of the most awarded games in history.)																							
db.session.add(g71)																							
g72= Game(title=The Last of Us Part II, release=2020, platforms=PlayStation 4, description=Sequel to The Last of Us  an action-adventure survival horror video game. Played from a third-person perspective; players use firearms and improvised weapons  and can use stealth to defend against hostile humans and cannibalistic creatures.)																							
db.session.add(g72)																							
g73= Game(title=Left 4 Dead series, release=2008–2009, platforms=macOS  Windows  Xbox 360, description=Multiplayer first-person shooter games in which four survivors must cooperate to survive against the hordes of the infected and mutated monsters in an apocalyptic pandemic.)																							
db.session.add(g73)																							
g74= Game(title=Little Red Riding Hood's Zombie BBQ, release=2008, platforms=Nintendo DS, description=A surreal game where an outbreak of zombies infects many classic fairy tale settings  leaving only Little Red Riding Hood and Momotarō to defend themselves from the invasion.)																							
db.session.add(g74)																							
g75= Game(title=Lollipop Chainsaw, release=2012, platforms=PlayStation 3  Xbox 360, description=An action game which stars a chainsaw-wielding cheerleader who must rid her high school of zombies.)																							
db.session.add(g75)																							
g76= Game(title=Martian Gothic: Unification, release=2000, platforms=PlayStation  Windows, description=A science fiction survival horror. A trio of astronauts must combat zombies while solving puzzles and piecing together what happened to a research colony on Mars.)																							
db.session.add(g76)																							
g77= Game(title=MediEvil series, release=1998–2007, platforms=PlayStation  PlayStation 3  PlayStation Portable  PlayStation 4 (remake), description=The series stars Sir Dan  a cowardly knight slain by a wizard's army. 100 years later the same wizard casts a spell to raise an army of undead  raising Sir Dan in the process.)																							
db.session.add(g77)																							
g78= Game(title=Minecraft, release=2009, platforms=Windows  Xbox 360  iOS, description=A survival sandbox game where the player needs to survive by building a shelter  and building tools to keep zombies and other monsters away.)																							
db.session.add(g78)																							
g79= Game(title=Monkey Island 2: LeChuck's Revenge, release=1991, platforms=Amiga  DOS  FM Towns  Mac OS, description=Graphic adventure game. The series' antagonist  LeChuck the pirate  is reanimated as a zombie.)																							
db.session.add(g79)																							
g80= Game(title=Night Slashers, release=1993, platforms=Arcade, description=)																							
db.session.add(g80)																							
g81= Game(title=Nightmare Creatures, release=1997-1998, platforms=PlayStation  Windows  Nintendo 64, description=A survival horror game based in the nineteenth century. A devil-worshipping cult called 'The brotherhood of the Hecate' perform ungodly experiments in London to try to create super-humans but instead makes horrid monsters. It contains a wide array of creatures including zombies.)																							
db.session.add(g81)																							
g82= Game(title=No More Room in Hell, release=2011–present, platforms=Windows  Linux  macOS  SteamOS, description=A multiplayer-focused survival game  initially created as a Source Engine mod. The game mainly focuses on co-operation and survival rather than dispatching zombies. Heavily inspired by George Romero's Living Dead series  the zombies are mainly slow-moving and are dangerous in large formed groups  though freshly turned cadavers as well as reanimated children move faster due to the lack of rigor mortis.)																							
db.session.add(g82)																							
g83= Game(title=The OneChanbara series, release=2000–present, platforms=PlayStation 2  PlayStation 3  PlayStation 4  PlayStation Portable  Wii  Xbox 360, description=Hack and slash games involving a bikini-clad female protagonist cutting swathes through an army of undead with a katana.)																							
db.session.add(g83)																							
g84= Game(title=Pixel Force: Left 4 Dead, release=2010, platforms=Windows, description=A fan remake of Left 4 Dead. Unlike the source game  a first-person shooter  this game is an overhead shooter.)																							
db.session.add(g84)																							
g85= Game(title=Plague Inc., release=2012, platforms=iOS  Android  Windows Phone  Microsoft Windows, description=A real-time strategy simulation game in which the player can evolve different pathogens in order to extinct the human race. Players have the option to play as a zombie plague called the Necroa Virus. Once zombified  humans cannot be cured  so an anti-zombie force called Z-Com becomes the biggest enemy for the player.)																							
db.session.add(g85)																							
g86= Game(title=Plants vs. Zombies, release=2009, platforms=macOS  Windows  Xbox 360  iOS  PlayStation 3, description=Tower defence game featuring a homeowner defending their home against zombies  which must be defeated by an assortment of plants with different offensive abilities.)																							
db.session.add(g86)																							
g87= Game(title=Plants vs. Zombies: Garden Warfare, release=2014, platforms=Windows  PlayStation 4  PlayStation 3  Xbox One  Xbox 360, description=A third person shooter game based on the original Plants vs. Zombies game. It features several new game modes.)																							
db.session.add(g87)																							
g88= Game(title=Plants vs. Zombies: Garden Warfare 2, release=2016 release, platforms=Windows  PlayStation 4  Xbox One, description=A sequel to the 2014 game.)																							
db.session.add(g88)																							
g89= Game(title=Postal 2: Apocalypse Weekend, release=2005, platforms=Linux  macOS  Windows, description=Expansion pack for first-person shooter game Postal 2 featuring a zombie attack on the fictitious town of Paradise.)																							
db.session.add(g89)																							
g90= Game(title=Project Zomboid, release=Pre-release, platforms=Linux  macOS  Windows, description=An isometric zombie survival role-playing game under ongoing development.)																							
db.session.add(g90)																							
g91= Game(title=Realm of Impossibility, release=1984, platforms=Apple IIe  Atari 8-bit family  Commodore 64  ZX Spectrum, description=An isometric action adventure game with 13 levels. Zombies  spiders and snakes must be avoided in order to reclaim the crowns stolen by an evil cleric.)																							
db.session.add(g91)																							
g92= Game(title=Red Dead Redemption: Undead Nightmare, release=2010, platforms=PlayStation 3  Xbox 360, description=Downloadable content for the open-world wild west game Red Dead Redemption. Players try to find a cure for the plague which is turning locals into zombies.)																							
db.session.add(g92)																							
g93= Game(title=Resident Evil series, release=1996–present, platforms=Various, description=Survival horror series featuring flesh-eating zombies created by synthetic means  such as infection with the fictional T-virus.)																							
db.session.add(g93)																							
g94= Game(title=Return to Castle Wolfenstein, release=2001, platforms=Linux  macOS  PlayStation 2  Windows  Xbox, description=First-person shooter from the Wolfenstein series  players fight Nazi soldiers and numerous zombies. The object of the game is to prevent the raising of an army of undead Nazis.)																							
db.session.add(g94)																							
g95= Game(title=Rise of Nightmares, release=2011, platforms=Xbox 360, description=The game uses full-body control via the Kinect motion sensor  players attack zombies using different types of weapons which degrade over time.)																							
db.session.add(g95)																							
g96= Game(title=Rock of the Dead, release=2010, platforms=PlayStation 3  Xbox 360, description=Players must bring down attacking zombies with music by using a guitar controller.)																							
db.session.add(g96)																							
g97= Game(title=Shadow Man, release=1999, platforms=Dreamcast  Nintendo 64  PlayStation  Windows, description=Players assume the role of Mike Leroi  who is cursed to be a zombie slave but has also been chosen to be the Shadow Man. Shadow Man is able to travel between the living world and Deadside  which features zombies and flying corpses.)																							
db.session.add(g97)																							
g98= Game(title=Shellshock 2: Blood Trails, release=2009, platforms=PlayStation 3  Windows  Xbox 360, description=First-person shooter  a zombie outbreak in Vietnam during the Vietnam War is caused by a virus called WhiteKnight.)																							
db.session.add(g98)																							
g99= Game(title=Siren series, release=2003–2008, platforms=PlayStation 2  PlayStation 3, description=Survival horror series. The primary enemies of the game  'shibito' (屍人)  are living dead who can be 'sightjacked' by the player  allowing them to observe the gameworld through the shibito's eyes.)																							
db.session.add(g99)																							
g100= Game(title=Space Pirates and Zombies, release=2011, platforms=Windows, description=A shooter game set in space  containing role-playing and strategy elements. The titular zombies emerge late in the game and operate in a similar manner to the Borg of Star Trek  by assimilating space ships and crew into an undead horde.)																							
db.session.add(g100)																							
g101= Game(title=State of Decay, release=2013, platforms=Windows  Xbox Live Arcade, description=Unlike games such as Left 4 Dead and Dead Island  State of Decay will focus more on survival  stealth  evasion  distractions  securing the player's resources  and moving through the world than actual zombie combat.)																							
db.session.add(g101)																							
g102= Game(title=State of Decay 2, release=2018, platforms=Windows  Xbox One, description=Sequel to State of Decay. It places emphasis on how the player's leaderships skills fare against an onslaught of problems  such as diminishing survival resources  group trust and morale  zombie extermination  base defenses  and people's lives. The game combines elements of shooters  stealth  role-playing and strategy games and the game challenges players to survive by exploring  scavenging  and fighting the undead.)																							
db.session.add(g102)																							
g103= Game(title=Stubbs the Zombie in Rebel Without a Pulse, release=2005, platforms=macOS  Windows  Xbox  Xbox 360, description=A third-person comedy game played as the titular zombie. Humans are converted into zombies when killed by Stubbs  creating an army of zombies.)																							
db.session.add(g103)																							
g104= Game(title=Survival Crisis Z, release=2004, platforms=Windows, description=Features two different play modes  story and arcade  the former involves surviving a zombie holocaust by scavenging and interacting with other survivors  the latter is a straightforward shooter game.)																							
db.session.add(g104)																							
g105= Game(title=Sweet Home, release=1989, platforms=Family Computer, description=One of the first survival horror games  it featured zombies as enemies representing previous visitors who never made it out of the mansion alive.)																							
db.session.add(g105)																							
g106= Game(title=Teenage Zombies: Invasion of the Alien Brain Thingys!, release=2008, platforms=Nintendo DS, description=Platform game with puzzle elements  players control three zombies with different abilities in order to thwart the alien brains which have invaded Earth.)																							
db.session.add(g106)																							
g107= Game(title=They Hunger series, release=1999, platforms=Windows, description=A trilogy of single-player mods for Half-Life  the first is set in a rural area of the United States of America. Later in the series settings such as missile silos are explored.)																							
db.session.add(g107)																							
g108= Game(title=TimeSplitters: Future Perfect, release=2005, platforms=PS2  Xbox  GameCube, description=The third installment of the popular time travel-themed first-person shooter contained playable multiplayer characters and enemy AI that are commonly referred to as Zombies.)																							
db.session.add(g108)																							
g109= Game(title=Touch the Dead, release=2007, platforms=Nintendo DS, description=On-rail  first-person shooter. A prisoner named Rob Steiner escapes from jail while battling countless zombies  the player attacks by using the console's touchscreen.)																							
db.session.add(g109)																							
g110= Game(title=The Typing of the Dead, release=1999, platforms=Dreamcast  Windows, description=A touch typing trainer version of The House of the Dead 2.)																							
db.session.add(g110)																							
g111= Game(title=Undead Knights, release=2009, platforms=PlayStation Portable, description=A hack 'n slash game featuring a trio of undead knights who can reanimate their victims as zombies and send them into battle.)																							
db.session.add(g111)																							
g112= Game(title=Unturned, release=2014, platforms=PlayStation 4  Mac  Windows  Xbox One  Xbox Series X, description=A multiplayer survival game described by one critic as a combination of Dayz and Minecraft. The game uses the free-to-play payment model.)																							
db.session.add(g112)																							
g113= Game(title=Urban Dead, release=2005, platforms=Browser, description=A massively multiplayer online game where players choose whether to play as a human survivor or a zombie in the battle for control of a quarantined city.)																							
db.session.add(g113)																							
g114= Game(title=Voodoo Kid, release=1997, platforms=Windows, description=The artistic concept of the game is heavily based on voodoo culture. All characters excluding the unnamed protagonist are soulless zombies bounded to a ghost ship.)																							
db.session.add(g114)																							
g115= Game(title=The Walking Dead, release=2012, platforms=Android  iOS  Kindle Fire HDX  macOS  PlayStation 3  PlayStation 4  Ouya  PlayStation Vita  Windows  Xbox 360  Xbox One, description=Based on the comic series and being developed by Telltale Games  this licensed video game is due to be 'multi-year  multi-platform  multi-title'.)																							
db.session.add(g115)																							
g116= Game(title=The Walking Dead: Survival Instinct, release=2013, platforms=PlayStation 3  Wii U  Windows  Xbox 360, description=)																							
db.session.add(g116)																							
g117= Game(title=Warcraft III series, release=2002-2003, platforms=Mac OS  macOS  Windows, description=The Undead Scourge race contains classic flesh-consuming zombies (Ghouls and Abominations). The Forsaken race in the later World of Warcraft MMORPG are zombies who had rebelled against the Scourge.)																							
db.session.add(g117)																							
g118= Game(title=World of the Living Dead Resurrection, release=2013, platforms=Browser, description=Survival Strategy Browser Game currently in closed beta testing. Players compete for resources in order to keep their group of survivors alive in a zombie plagued Los Angeles.)																							
db.session.add(g118)																							
g119= Game(title=World War Z, release=2019, platforms=Microsoft Windows  PlayStation 4  Xbox One, description=The game is a co-operative  third-person shooter in which 4 players fight against massive hordes of zombies in locations including: New York  Jerusalem  Moscow  Tokyo  and Marseille  France.)																							
db.session.add(g119)																							
g120= Game(title=The X-Files: Resist or Serve, release=2004, platforms=PlayStation 2, description=A survival horror game based on the television series  The X-Files. The player can play as either Fox Mulder or Dana Scully  who are investigating a town overrun by zombies.)																							
db.session.add(g120)																							
g121= Game(title=Yakuza: Dead Souls, release=2011, platforms=PlayStation 3, description=Part of Sega's Yakuza series  the martial combat of previous titles has been replaced with an emphasis on gun battles. The city has been infected with a zombie plague and now a third of the population are zombies.)																							
db.session.add(g121)																							
g122= Game(title=Zafehouse: Diaries series, release=2012, platforms=Windows, description=Single-player turn-based strategy games  portrayed mostly via a map and diary. The games require management of survivors' interpersonal relationships in addition to standard zombie survival actions.)																							
db.session.add(g122)																							
g123= Game(title=Zombi, release=1986, platforms=Amiga  Amstrad CPC  Atari ST  Commodore 64  Commodore Plus/4  ZX Spectrum, description=Icon-driven graphic adventure inspired by the film Dawn of the Dead. A group of survivors is forced to land their helicopter atop a zombie infested shopping mall  the vehicle must be refueled so they can escape.)																							
db.session.add(g123)																							
g124= Game(title=Zombie Army Trilogy, release=2015, platforms=Microsoft Windows  PlayStation 4  Xbox One, description=A third person zombie shooter set during world war 2)																							
db.session.add(g124)																							
g125= Game(title=Zombie Army 4: Dead War, release=2020, platforms=Microsoft Windows  PlayStation 4  Xbox One, description=A third person zombie shooter set during world war 2. It is a sequel to Zombie Army Trilogy.)																							
db.session.add(g125)																							
g126= Game(title=Zombie Apocalypse, release=2009, platforms=PlayStation 3  Xbox 360, description=The player has to shoot or decapitate zombies across seven different areas.)																							
db.session.add(g126)																							
g127= Game(title=Zombie Driver, release=2009, platforms=Windows, description=An overhead-view mission-based driving game taking place in a zombie apocalypse.)																							
db.session.add(g127)																							
g128= Game(title=Zombie Gunship, release=2011, platforms=iOS, description=Players act as the gunner on an AC-130U Spectre gunship. The object is to destroy as many zombies and monsters as possible  while helping as many human civilians as possible reach the safety of a bunker  before the zombies reach the bunker or too many friendly fire incidents occur.)																							
db.session.add(g128)																							
g129= Game(title=The Zombie Island of Dr. Ned, release=2009, platforms=PlayStation 3  Windows  Xbox 360, description=Zombie-themed downloadable content for Borderlands featuring a swamp island filled with undead.)																							
db.session.add(g129)																							
g130= Game(title=Zombie Lane, release=2011, platforms=Facebook  Google+  iOS, description=A top-down/third person social networking Facebook game. Players must repair their neighbourhood after a zombie apocalypse and locate their missing wife and dog.)																							
db.session.add(g130)																							
g131= Game(title=Zombie Massacre, release=1998, platforms=Amiga, description=First-person shooter  clone of the popular Amiga first person shooter Doom)																							
db.session.add(g131)																							
g132= Game(title=Zombie Nation, release=1990, platforms=NES, description=Shoot 'em up in which players control a disembodied samurai's head. A mysterious meteor called Darc Seed crashes to Earth and turns the inhabitants of the United States into zombies.)																							
db.session.add(g132)																							
g133= Game(title=Zombie Panic! Source, release=2007, platforms=Windows, description=A multiplayer Half-Life 2 mod  in which players are divided into two teams  survivors and zombies. When survivors are killed  they become zombies.)																							
db.session.add(g133)																							
g134= Game(title=Zombie Parkour Runner, release=2011, platforms=iOS, description=A parkour game where the player must retrieve the items stolen from them by zombies.)																							
db.session.add(g134)																							
g135= Game(title=Zombie Revenge, release=1999, platforms=Arcade  Dreamcast, description=Beat 'em up where players choose one of three characters to pummel zombies.)																							
db.session.add(g135)																							
g136= Game(title=Zombie Tycoon, release=2009, platforms=PlayStation Portable, description=Downloadable real-time strategy game. Players control three teams of up to eight zombies to attack the living.)																							
db.session.add(g136)																							
g137= Game(title=Zombie Wranglers, release=2009, platforms=Xbox 360, description=An Xbox Live game where players choose one of four characters to 'wrangle' zombies through twenty levels.)																							
db.session.add(g137)																							
g138= Game(title=Zombie Zombie, release=1984, platforms=ZX Spectrum, description=The player must rid a city of the undead by luring them over the edge of structures. These can be constructed with a helicopter  which can be landed to allow the zombies to pursue the player character.)																							
db.session.add(g138)																							
g139= Game(title=Zombies, release=2011, platforms=Windows Phone  Xbox 360, description=)																							
db.session.add(g139)																							
g140= Game(title=Zombies Ate My Neighbors, release=1993, platforms=Genesis  Super NES, description=Shooter game played from an overhead perspective. The game parodies B-movies and features zombies amongst several other types of monster.)																							
db.session.add(g140)																							
g141= Game(title=Zombies  Run!, release=2012, platforms=iOS  Android, description=An immersive running game.)																							
db.session.add(g141)																							
g142= Game(title=ZombiU, release=2012, platforms=Wii U, description=A 2012 survival horror game. The player controls a random survivor who must attempt to survive a zombie apocalypse running amok in London.)																							
db.session.add(g142)																																													
"""

